### ISSUE TITLE
Framework blogs

### ISSUE THREAD

**Issue by yoshuawuyts** [rustasync/team#61]
# Framework blogs

As proposed by @majorbreakfast in the [last Net WG Lead meeting](https://github.com/rust-lang-nursery/wg-net/blob/master/meetings/2018-08-31-net-wg-leads.md), it'd be
great to talk with different framework authors in the blog.

The idea is that we encourage authors to present their framework in a blog post,
according to a limited length format that can be followed. That way we can
let authors describe their projects themselves rather than by someone else.

To kick this off we would need to do the following:

1. Find someone who is willing to reach out to framework authors, follow up
   with them, and publish the posts.
2. Outline the questions to ask the authors. We can probably workshop the
   questions in this issue.
3. Find a first author + framework to highlight.

If this sounds like something you'd like to work on, or you have great ideas to
make this series successful, comment below and we can get the ball rolling!

## Tasks
- [ ] Assign responsibility for publishing
- [ ] Outline questions to ask
- [ ] Find first framework to highlight
- [ ] Reach out to more framework authors for follow-up posts

**Comment by rolftimmermans** [comment]
Some ideas for questions:

* What brought you to create <framework>?
* What advantages does Rust bring for web application developers? How does <framework> fit into this?
* What part of <framework> was most challenging to implement?
* What sort of applications do you see benefiting most from <framework> and from being written in Rust?
